name: SkinStealer
main: SkinStealer\SkinStealer
api: [3.0.0, 4.0.0]
version: 1.0.0
authors: [DRAGKILLS, SeakHai]

commands:
  skin:
    description: "skinstealer"
    permission: skin.stealer

permissions:
  skin.stealer:
    description: "/skin"
